-- Jeu de données de départ, GÉNÉRÉ par scripts/seed-sql.mjs depuis packages/core/src/seed.ts.
-- Ne pas modifier à la main : relancer `node scripts/seed-sql.mjs`.
-- Rejouable : chaque ligne est insérée ou mise à jour (on conflict do update).

begin;

-- Catégories
insert into public.categories (id, slug, name, description, image, sort)
values ('cat-volailles', 'volailles-entieres', '{"fr":"Volailles entières","ar":"دواجن كاملة"}'::jsonb, '{"fr":"Poulets et poules élevés en plein air, abattus le matin de votre livraison.","ar":"دجاج بلدي مرباة في الهواء الطلق، تُذبح صباح يوم التوصيل."}'::jsonb, '/images/products/poulet-entier.jpg', 1)
on conflict (id) do update set slug = excluded.slug, name = excluded.name, description = excluded.description, image = excluded.image, sort = excluded.sort;
insert into public.categories (id, slug, name, description, image, sort)
values ('cat-decoupes', 'decoupes', '{"fr":"Découpes de poulet","ar":"قطع الدجاج"}'::jsonb, '{"fr":"Cuisses, escalopes, ailes et pilons, découpés à la demande.","ar":"أفخاذ، إسكالوب، أجنحة وسيقان، تُقطّع عند الطلب."}'::jsonb, '/images/products/escalope-poulet.jpg', 2)
on conflict (id) do update set slug = excluded.slug, name = excluded.name, description = excluded.description, image = excluded.image, sort = excluded.sort;
insert into public.categories (id, slug, name, description, image, sort)
values ('cat-dinde', 'dinde', '{"fr":"Dinde","ar":"ديك رومي"}'::jsonb, '{"fr":"Escalopes et filets de dinde, tendres et maigres.","ar":"إسكالوب وفيليه ديك رومي، طري وقليل الدهن."}'::jsonb, '/images/products/dinde-escalope.jpg', 3)
on conflict (id) do update set slug = excluded.slug, name = excluded.name, description = excluded.description, image = excluded.image, sort = excluded.sort;
insert into public.categories (id, slug, name, description, image, sort)
values ('cat-oeufs', 'oeufs', '{"fr":"Œufs fermiers","ar":"بيض بلدي"}'::jsonb, '{"fr":"Ramassés chaque matin. Jaune orangé, coquille solide.","ar":"يُجمع كل صباح. صفار برتقالي وقشرة صلبة."}'::jsonb, '/images/products/oeufs.jpg', 4)
on conflict (id) do update set slug = excluded.slug, name = excluded.name, description = excluded.description, image = excluded.image, sort = excluded.sort;
insert into public.categories (id, slug, name, description, image, sort)
values ('cat-charcuterie', 'charcuterie', '{"fr":"Charcuterie de volaille","ar":"شاركوتري الدواجن"}'::jsonb, '{"fr":"Merguez, saucisses, jambon et salami de volaille, faits à la ferme.","ar":"مرقاز، سجق، جامبون وسلامي دواجن، مصنوعة في المزرعة."}'::jsonb, '/images/products/charcuterie-volaille.jpg', 5)
on conflict (id) do update set slug = excluded.slug, name = excluded.name, description = excluded.description, image = excluded.image, sort = excluded.sort;
insert into public.categories (id, slug, name, description, image, sort)
values ('cat-marines', 'marines', '{"fr":"Marinés et prêts à cuire","ar":"متبّل وجاهز للطهي"}'::jsonb, '{"fr":"Brochettes, cuisses marinées et nuggets maison. Il ne reste qu’à cuire.","ar":"أسياخ، أفخاذ متبّلة وناغتس منزلية. ما عليك إلا الطهي."}'::jsonb, '/images/products/brochettes.jpg', 6)
on conflict (id) do update set slug = excluded.slug, name = excluded.name, description = excluded.description, image = excluded.image, sort = excluded.sort;

-- Produits
insert into public.products (id, slug, category_id, name, short, description, images, pricing, compare_at, badges, stock, is_featured, sort, tips)
values ('p-poulet-fermier', 'poulet-fermier-entier', 'cat-volailles', '{"fr":"Poulet fermier entier","ar":"دجاج بلدي كامل"}'::jsonb, '{"fr":"Élevé 90 jours en plein air, environ 1,7 kg","ar":"مرباة 90 يوماً في الهواء الطلق، حوالي 1.7 كغ"}'::jsonb, '{"fr":"Notre poulet fermier grandit lentement, dehors, nourri au grain. Chair ferme et goûteuse, peau dorée à la cuisson. Livré entier, vidé et prêt à rôtir. Le prix est ajusté au poids réel à la pesée.","ar":"ينمو دجاجنا البلدي ببطء في الهواء الطلق ويتغذى على الحبوب. لحم متماسك ولذيذ وجلد ذهبي عند الطهي. يُسلَّم كاملاً ومنظفاً وجاهزاً للشوي. يُعدَّل السعر حسب الوزن الحقيقي عند الوزن."}'::jsonb, array['/images/products/poulet-entier.jpg']::text[], '{"mode":"per_kg_estimated","price_per_kg":14.9,"est_weight_kg":1.7,"min_weight_kg":1.4,"max_weight_kg":2.1,"max_qty":10}'::jsonb, null, array['fermier', 'best']::text[], 'en_stock', true, 1, '{"fr":"Se conserve 3 jours au réfrigérateur. Sortez-le 30 min avant de le cuire.","ar":"يُحفظ 3 أيام في الثلاجة. أخرجه قبل الطهي بـ30 دقيقة."}'::jsonb)
on conflict (id) do update set slug = excluded.slug, category_id = excluded.category_id, name = excluded.name, short = excluded.short, description = excluded.description, images = excluded.images, pricing = excluded.pricing, compare_at = excluded.compare_at, badges = excluded.badges, stock = excluded.stock, is_featured = excluded.is_featured, sort = excluded.sort, tips = excluded.tips;
insert into public.products (id, slug, category_id, name, short, description, images, pricing, compare_at, badges, stock, is_featured, sort, tips)
values ('p-poulet-petit', 'petit-poulet-fermier', 'cat-volailles', '{"fr":"Petit poulet fermier","ar":"دجاج بلدي صغير"}'::jsonb, '{"fr":"Pour 2 personnes, environ 1,2 kg","ar":"لشخصين، حوالي 1.2 كغ"}'::jsonb, '{"fr":"Le même poulet fermier, en plus petit format. Parfait pour un dîner à deux ou un poulet rôti du dimanche sans restes.","ar":"نفس الدجاج البلدي بحجم أصغر. مثالي لعشاء لشخصين أو دجاج مشوي دون بقايا."}'::jsonb, array['/images/products/poulet-entier.jpg']::text[], '{"mode":"per_kg_estimated","price_per_kg":14.9,"est_weight_kg":1.2,"min_weight_kg":1,"max_weight_kg":1.4,"max_qty":10}'::jsonb, null, array['fermier']::text[], 'en_stock', false, 2, null)
on conflict (id) do update set slug = excluded.slug, category_id = excluded.category_id, name = excluded.name, short = excluded.short, description = excluded.description, images = excluded.images, pricing = excluded.pricing, compare_at = excluded.compare_at, badges = excluded.badges, stock = excluded.stock, is_featured = excluded.is_featured, sort = excluded.sort, tips = excluded.tips;
insert into public.products (id, slug, category_id, name, short, description, images, pricing, compare_at, badges, stock, is_featured, sort, tips)
values ('p-poule', 'poule-fermiere', 'cat-volailles', '{"fr":"Poule fermière","ar":"دجاجة بلدية"}'::jsonb, '{"fr":"Pour le couscous et les bouillons, environ 2 kg","ar":"للكسكسي والمرق، حوالي 2 كغ"}'::jsonb, '{"fr":"La poule de réforme, celle de nos grands-mères. Chair plus ferme, goût profond : c’est elle qui fait le vrai bouillon du couscous et de la chorba.","ar":"دجاجة بلدية كبيرة كما كانت جداتنا تطهوها. لحم أكثر تماسكاً وطعم عميق: هي سر مرق الكسكسي والشوربة."}'::jsonb, array['/images/products/poules-plein-air.jpg']::text[], '{"mode":"per_kg_estimated","price_per_kg":12.5,"est_weight_kg":2,"min_weight_kg":1.7,"max_weight_kg":2.5,"max_qty":6}'::jsonb, null, array['fermier']::text[], 'en_stock', false, 3, null)
on conflict (id) do update set slug = excluded.slug, category_id = excluded.category_id, name = excluded.name, short = excluded.short, description = excluded.description, images = excluded.images, pricing = excluded.pricing, compare_at = excluded.compare_at, badges = excluded.badges, stock = excluded.stock, is_featured = excluded.is_featured, sort = excluded.sort, tips = excluded.tips;
insert into public.products (id, slug, category_id, name, short, description, images, pricing, compare_at, badges, stock, is_featured, sort, tips)
values ('p-cuisses', 'cuisses-de-poulet', 'cat-decoupes', '{"fr":"Cuisses de poulet","ar":"أفخاذ دجاج"}'::jsonb, '{"fr":"Cuisses entières, avec peau","ar":"أفخاذ كاملة، مع الجلد"}'::jsonb, '{"fr":"Cuisses entières de poulet fermier, haut et pilon attachés. La pièce préférée pour le four, la braise et le tajine.","ar":"أفخاذ دجاج بلدي كاملة، الفخذ والساق معاً. القطعة المفضلة للفرن والشواء والطاجين."}'::jsonb, array['/images/products/cuisses-poulet.jpg']::text[], '{"mode":"per_kg","price_per_kg":15.9,"step_kg":0.5,"min_kg":0.5,"max_kg":10}'::jsonb, null, array['best']::text[], 'en_stock', true, 1, null)
on conflict (id) do update set slug = excluded.slug, category_id = excluded.category_id, name = excluded.name, short = excluded.short, description = excluded.description, images = excluded.images, pricing = excluded.pricing, compare_at = excluded.compare_at, badges = excluded.badges, stock = excluded.stock, is_featured = excluded.is_featured, sort = excluded.sort, tips = excluded.tips;
insert into public.products (id, slug, category_id, name, short, description, images, pricing, compare_at, badges, stock, is_featured, sort, tips)
values ('p-escalopes', 'escalopes-de-poulet', 'cat-decoupes', '{"fr":"Escalopes de poulet","ar":"إسكالوب دجاج"}'::jsonb, '{"fr":"Blanc de poulet tranché fin","ar":"صدر دجاج مقطّع رقيق"}'::jsonb, '{"fr":"Blancs de poulet fermier tranchés en escalopes régulières. Sans os, sans peau. Pour les paniers, les salades et les plats rapides de la semaine.","ar":"صدور دجاج بلدي مقطّعة إلى شرائح منتظمة. بدون عظم ولا جلد. للبانيه والسلطات وأطباق الأسبوع السريعة."}'::jsonb, array['/images/products/escalope-poulet.jpg']::text[], '{"mode":"per_kg","price_per_kg":22.9,"step_kg":0.25,"min_kg":0.5,"max_kg":10}'::jsonb, null, array['best']::text[], 'en_stock', true, 2, null)
on conflict (id) do update set slug = excluded.slug, category_id = excluded.category_id, name = excluded.name, short = excluded.short, description = excluded.description, images = excluded.images, pricing = excluded.pricing, compare_at = excluded.compare_at, badges = excluded.badges, stock = excluded.stock, is_featured = excluded.is_featured, sort = excluded.sort, tips = excluded.tips;
insert into public.products (id, slug, category_id, name, short, description, images, pricing, compare_at, badges, stock, is_featured, sort, tips)
values ('p-ailes', 'ailes-de-poulet', 'cat-decoupes', '{"fr":"Ailes de poulet","ar":"أجنحة دجاج"}'::jsonb, '{"fr":"Pour la braise et le four","ar":"للشواء والفرن"}'::jsonb, '{"fr":"Ailes entières, charnues, idéales grillées avec un peu de harissa et de citron.","ar":"أجنحة كاملة ولحيمة، مثالية مشوية مع قليل من الهريسة والليمون."}'::jsonb, array['/images/products/ailes-poulet.jpg']::text[], '{"mode":"per_kg","price_per_kg":11.9,"step_kg":0.5,"min_kg":0.5,"max_kg":10}'::jsonb, null, '{}'::text[], 'en_stock', false, 3, null)
on conflict (id) do update set slug = excluded.slug, category_id = excluded.category_id, name = excluded.name, short = excluded.short, description = excluded.description, images = excluded.images, pricing = excluded.pricing, compare_at = excluded.compare_at, badges = excluded.badges, stock = excluded.stock, is_featured = excluded.is_featured, sort = excluded.sort, tips = excluded.tips;
insert into public.products (id, slug, category_id, name, short, description, images, pricing, compare_at, badges, stock, is_featured, sort, tips)
values ('p-pilons', 'pilons-de-poulet', 'cat-decoupes', '{"fr":"Pilons de poulet","ar":"سيقان دجاج"}'::jsonb, '{"fr":"Les préférés des enfants","ar":"المفضلة عند الأطفال"}'::jsonb, '{"fr":"Pilons de poulet fermier, faciles à tenir, faciles à cuire. Au four, en 35 minutes, avec des pommes de terre.","ar":"سيقان دجاج بلدي، سهلة الإمساك وسهلة الطهي. في الفرن خلال 35 دقيقة مع البطاطا."}'::jsonb, array['/images/products/pilons-poulet.jpg']::text[], '{"mode":"per_kg","price_per_kg":14.5,"step_kg":0.5,"min_kg":0.5,"max_kg":10}'::jsonb, null, '{}'::text[], 'en_stock', false, 4, null)
on conflict (id) do update set slug = excluded.slug, category_id = excluded.category_id, name = excluded.name, short = excluded.short, description = excluded.description, images = excluded.images, pricing = excluded.pricing, compare_at = excluded.compare_at, badges = excluded.badges, stock = excluded.stock, is_featured = excluded.is_featured, sort = excluded.sort, tips = excluded.tips;
insert into public.products (id, slug, category_id, name, short, description, images, pricing, compare_at, badges, stock, is_featured, sort, tips)
values ('p-dinde-escalope', 'escalopes-de-dinde', 'cat-dinde', '{"fr":"Escalopes de dinde","ar":"إسكالوب ديك رومي"}'::jsonb, '{"fr":"Maigres et tendres","ar":"قليلة الدهن وطرية"}'::jsonb, '{"fr":"Escalopes de dinde tranchées le jour même. Très maigres, elles conviennent aux grillades et aux régimes.","ar":"إسكالوب ديك رومي مقطّع في نفس اليوم. قليل الدهن جداً، مناسب للشواء والحمية."}'::jsonb, array['/images/products/dinde-escalope.jpg']::text[], '{"mode":"per_kg","price_per_kg":23.9,"step_kg":0.25,"min_kg":0.5,"max_kg":10}'::jsonb, null, '{}'::text[], 'en_stock', false, 1, null)
on conflict (id) do update set slug = excluded.slug, category_id = excluded.category_id, name = excluded.name, short = excluded.short, description = excluded.description, images = excluded.images, pricing = excluded.pricing, compare_at = excluded.compare_at, badges = excluded.badges, stock = excluded.stock, is_featured = excluded.is_featured, sort = excluded.sort, tips = excluded.tips;
insert into public.products (id, slug, category_id, name, short, description, images, pricing, compare_at, badges, stock, is_featured, sort, tips)
values ('p-dinde-filet', 'filet-de-dinde', 'cat-dinde', '{"fr":"Filet de dinde entier","ar":"فيليه ديك رومي كامل"}'::jsonb, '{"fr":"Pour rôtir ou farcir","ar":"للشوي أو الحشو"}'::jsonb, '{"fr":"Le filet entier, à rôtir doucement ou à farcir pour les grandes tablées.","ar":"الفيليه كاملاً، يُشوى على نار هادئة أو يُحشى للولائم."}'::jsonb, array['/images/products/dinde-escalope.jpg']::text[], '{"mode":"per_kg","price_per_kg":21.9,"step_kg":0.5,"min_kg":1,"max_kg":10}'::jsonb, null, '{}'::text[], 'bientot', false, 2, null)
on conflict (id) do update set slug = excluded.slug, category_id = excluded.category_id, name = excluded.name, short = excluded.short, description = excluded.description, images = excluded.images, pricing = excluded.pricing, compare_at = excluded.compare_at, badges = excluded.badges, stock = excluded.stock, is_featured = excluded.is_featured, sort = excluded.sort, tips = excluded.tips;
insert into public.products (id, slug, category_id, name, short, description, images, pricing, compare_at, badges, stock, is_featured, sort, tips)
values ('p-oeufs-6', 'oeufs-fermiers-x6', 'cat-oeufs', '{"fr":"Œufs fermiers, boîte de 6","ar":"بيض بلدي، علبة 6"}'::jsonb, '{"fr":"Ramassés ce matin","ar":"جُمع هذا الصباح"}'::jsonb, '{"fr":"Six œufs de poules élevées en plein air, ramassés le matin. Jaune orangé, blanc qui se tient.","ar":"ست بيضات من دجاج مرباة في الهواء الطلق، جُمعت صباحاً. صفار برتقالي وبياض متماسك."}'::jsonb, array['/images/products/oeufs.jpg']::text[], '{"mode":"per_piece","price":3.6,"max_qty":20}'::jsonb, null, array['fermier']::text[], 'en_stock', true, 1, '{"fr":"Se conservent 3 semaines au frais. Ne les lavez pas avant de les ranger.","ar":"يُحفظ 3 أسابيع في البرودة. لا تغسلها قبل التخزين."}'::jsonb)
on conflict (id) do update set slug = excluded.slug, category_id = excluded.category_id, name = excluded.name, short = excluded.short, description = excluded.description, images = excluded.images, pricing = excluded.pricing, compare_at = excluded.compare_at, badges = excluded.badges, stock = excluded.stock, is_featured = excluded.is_featured, sort = excluded.sort, tips = excluded.tips;
insert into public.products (id, slug, category_id, name, short, description, images, pricing, compare_at, badges, stock, is_featured, sort, tips)
values ('p-oeufs-12', 'oeufs-fermiers-x12', 'cat-oeufs', '{"fr":"Œufs fermiers, boîte de 12","ar":"بيض بلدي، علبة 12"}'::jsonb, '{"fr":"La boîte de la semaine","ar":"علبة الأسبوع"}'::jsonb, '{"fr":"Douze œufs fermiers dans une boîte en carton recyclable.","ar":"اثنتا عشرة بيضة بلدية في علبة كرتون قابلة لإعادة التدوير."}'::jsonb, array['/images/products/oeufs.jpg']::text[], '{"mode":"per_piece","price":6.9,"max_qty":20}'::jsonb, null, array['fermier', 'best']::text[], 'en_stock', false, 2, null)
on conflict (id) do update set slug = excluded.slug, category_id = excluded.category_id, name = excluded.name, short = excluded.short, description = excluded.description, images = excluded.images, pricing = excluded.pricing, compare_at = excluded.compare_at, badges = excluded.badges, stock = excluded.stock, is_featured = excluded.is_featured, sort = excluded.sort, tips = excluded.tips;
insert into public.products (id, slug, category_id, name, short, description, images, pricing, compare_at, badges, stock, is_featured, sort, tips)
values ('p-oeufs-30', 'oeufs-fermiers-plateau-30', 'cat-oeufs', '{"fr":"Œufs fermiers, plateau de 30","ar":"بيض بلدي، صينية 30"}'::jsonb, '{"fr":"Pour les familles et les restaurants","ar":"للعائلات والمطاعم"}'::jsonb, '{"fr":"Le plateau de trente, le meilleur prix à l’œuf.","ar":"صينية الثلاثين، أفضل سعر للبيضة."}'::jsonb, array['/images/products/oeufs.jpg']::text[], '{"mode":"per_piece","price":15.9,"max_qty":10}'::jsonb, null, array['fermier']::text[], 'en_stock', false, 3, null)
on conflict (id) do update set slug = excluded.slug, category_id = excluded.category_id, name = excluded.name, short = excluded.short, description = excluded.description, images = excluded.images, pricing = excluded.pricing, compare_at = excluded.compare_at, badges = excluded.badges, stock = excluded.stock, is_featured = excluded.is_featured, sort = excluded.sort, tips = excluded.tips;
insert into public.products (id, slug, category_id, name, short, description, images, pricing, compare_at, badges, stock, is_featured, sort, tips)
values ('p-merguez', 'merguez-de-volaille', 'cat-charcuterie', '{"fr":"Merguez de volaille","ar":"مرقاز دواجن"}'::jsonb, '{"fr":"Épicées comme il faut","ar":"متبّلة كما يجب"}'::jsonb, '{"fr":"Merguez de poulet et de dinde, harissa et épices de Nabeul. Faites à la ferme, sans colorant. Environ 12 merguez au kilo.","ar":"مرقاز دجاج وديك رومي، هريسة وتوابل نابل. مصنوع في المزرعة دون ملوّنات. حوالي 12 مرقازة في الكيلو."}'::jsonb, array['/images/products/merguez.jpg']::text[], '{"mode":"per_kg","price_per_kg":19.9,"step_kg":0.5,"min_kg":0.5,"max_kg":10}'::jsonb, null, array['best']::text[], 'en_stock', true, 1, null)
on conflict (id) do update set slug = excluded.slug, category_id = excluded.category_id, name = excluded.name, short = excluded.short, description = excluded.description, images = excluded.images, pricing = excluded.pricing, compare_at = excluded.compare_at, badges = excluded.badges, stock = excluded.stock, is_featured = excluded.is_featured, sort = excluded.sort, tips = excluded.tips;
insert into public.products (id, slug, category_id, name, short, description, images, pricing, compare_at, badges, stock, is_featured, sort, tips)
values ('p-saucisses', 'saucisses-de-poulet', 'cat-charcuterie', '{"fr":"Saucisses de poulet","ar":"سجق دجاج"}'::jsonb, '{"fr":"Nature, aux herbes","ar":"طبيعي بالأعشاب"}'::jsonb, '{"fr":"Saucisses de poulet aux herbes fraîches, douces, appréciées des enfants.","ar":"سجق دجاج بالأعشاب الطازجة، خفيف التوابل، يحبه الأطفال."}'::jsonb, array['/images/products/saucisses-volaille.jpg']::text[], '{"mode":"per_kg","price_per_kg":18.5,"step_kg":0.5,"min_kg":0.5,"max_kg":10}'::jsonb, null, '{}'::text[], 'en_stock', false, 2, null)
on conflict (id) do update set slug = excluded.slug, category_id = excluded.category_id, name = excluded.name, short = excluded.short, description = excluded.description, images = excluded.images, pricing = excluded.pricing, compare_at = excluded.compare_at, badges = excluded.badges, stock = excluded.stock, is_featured = excluded.is_featured, sort = excluded.sort, tips = excluded.tips;
insert into public.products (id, slug, category_id, name, short, description, images, pricing, compare_at, badges, stock, is_featured, sort, tips)
values ('p-jambon', 'jambon-de-dinde-tranche', 'cat-charcuterie', '{"fr":"Jambon de dinde tranché, 200 g","ar":"جامبون ديك رومي مقطّع، 200 غ"}'::jsonb, '{"fr":"Pour les sandwichs du matin","ar":"لساندويتشات الصباح"}'::jsonb, '{"fr":"Jambon de dinde cuit à la ferme, tranché fin, en barquette de 200 g.","ar":"جامبون ديك رومي مطبوخ في المزرعة، مقطّع رقيقاً، في علبة 200 غ."}'::jsonb, array['/images/products/charcuterie-volaille.jpg']::text[], '{"mode":"per_piece","price":6.9,"max_qty":20}'::jsonb, null, '{}'::text[], 'en_stock', false, 3, null)
on conflict (id) do update set slug = excluded.slug, category_id = excluded.category_id, name = excluded.name, short = excluded.short, description = excluded.description, images = excluded.images, pricing = excluded.pricing, compare_at = excluded.compare_at, badges = excluded.badges, stock = excluded.stock, is_featured = excluded.is_featured, sort = excluded.sort, tips = excluded.tips;
insert into public.products (id, slug, category_id, name, short, description, images, pricing, compare_at, badges, stock, is_featured, sort, tips)
values ('p-salami', 'salami-de-volaille', 'cat-charcuterie', '{"fr":"Salami de volaille, 200 g","ar":"سلامي دواجن، 200 غ"}'::jsonb, '{"fr":"Tranché, prêt à servir","ar":"مقطّع وجاهز للتقديم"}'::jsonb, '{"fr":"Salami de volaille doux, tranché, en barquette de 200 g.","ar":"سلامي دواجن خفيف، مقطّع، في علبة 200 غ."}'::jsonb, array['/images/products/charcuterie-volaille.jpg']::text[], '{"mode":"per_piece","price":5.9,"max_qty":20}'::jsonb, null, array['nouveau']::text[], 'en_stock', false, 4, null)
on conflict (id) do update set slug = excluded.slug, category_id = excluded.category_id, name = excluded.name, short = excluded.short, description = excluded.description, images = excluded.images, pricing = excluded.pricing, compare_at = excluded.compare_at, badges = excluded.badges, stock = excluded.stock, is_featured = excluded.is_featured, sort = excluded.sort, tips = excluded.tips;
insert into public.products (id, slug, category_id, name, short, description, images, pricing, compare_at, badges, stock, is_featured, sort, tips)
values ('p-brochettes', 'brochettes-de-poulet-marinees', 'cat-marines', '{"fr":"Brochettes de poulet marinées","ar":"أسياخ دجاج متبّلة"}'::jsonb, '{"fr":"Citron, ail, épices","ar":"ليمون، ثوم، توابل"}'::jsonb, '{"fr":"Cubes de blanc de poulet marinés au citron, à l’ail et aux épices, sur pique en bois. Sur la braise en 10 minutes.","ar":"مكعبات صدر دجاج متبّلة بالليمون والثوم والتوابل على أسياخ خشبية. على الجمر خلال 10 دقائق."}'::jsonb, array['/images/products/brochettes.jpg']::text[], '{"mode":"per_kg","price_per_kg":24.9,"step_kg":0.5,"min_kg":0.5,"max_kg":10}'::jsonb, null, array['best']::text[], 'en_stock', true, 1, null)
on conflict (id) do update set slug = excluded.slug, category_id = excluded.category_id, name = excluded.name, short = excluded.short, description = excluded.description, images = excluded.images, pricing = excluded.pricing, compare_at = excluded.compare_at, badges = excluded.badges, stock = excluded.stock, is_featured = excluded.is_featured, sort = excluded.sort, tips = excluded.tips;
insert into public.products (id, slug, category_id, name, short, description, images, pricing, compare_at, badges, stock, is_featured, sort, tips)
values ('p-cuisses-marinees', 'cuisses-marinees', 'cat-marines', '{"fr":"Cuisses marinées","ar":"أفخاذ متبّلة"}'::jsonb, '{"fr":"Prêtes pour le four","ar":"جاهزة للفرن"}'::jsonb, '{"fr":"Cuisses de poulet fermier marinées la veille dans notre mélange maison. Au four, 45 minutes, c’est prêt.","ar":"أفخاذ دجاج بلدي متبّلة من الليلة السابقة بخلطتنا المنزلية. 45 دقيقة في الفرن وتكون جاهزة."}'::jsonb, array['/images/products/cuisses-poulet.jpg']::text[], '{"mode":"per_kg","price_per_kg":17.9,"step_kg":0.5,"min_kg":0.5,"max_kg":10}'::jsonb, null, '{}'::text[], 'en_stock', false, 2, null)
on conflict (id) do update set slug = excluded.slug, category_id = excluded.category_id, name = excluded.name, short = excluded.short, description = excluded.description, images = excluded.images, pricing = excluded.pricing, compare_at = excluded.compare_at, badges = excluded.badges, stock = excluded.stock, is_featured = excluded.is_featured, sort = excluded.sort, tips = excluded.tips;
insert into public.products (id, slug, category_id, name, short, description, images, pricing, compare_at, badges, stock, is_featured, sort, tips)
values ('p-nuggets', 'nuggets-maison-500g', 'cat-marines', '{"fr":"Nuggets maison, 500 g","ar":"ناغتس منزلية، 500 غ"}'::jsonb, '{"fr":"Du vrai blanc de poulet","ar":"من صدر دجاج حقيقي"}'::jsonb, '{"fr":"Nuggets faits avec du vrai blanc de poulet fermier, panés à la maison. Sachet de 500 g, environ 20 pièces.","ar":"ناغتس مصنوعة من صدر دجاج بلدي حقيقي، مغلّفة بالبقسماط في المزرعة. كيس 500 غ، حوالي 20 قطعة."}'::jsonb, array['/images/products/escalope-poulet.jpg']::text[], '{"mode":"per_piece","price":12.9,"max_qty":20}'::jsonb, null, array['nouveau']::text[], 'en_stock', false, 3, null)
on conflict (id) do update set slug = excluded.slug, category_id = excluded.category_id, name = excluded.name, short = excluded.short, description = excluded.description, images = excluded.images, pricing = excluded.pricing, compare_at = excluded.compare_at, badges = excluded.badges, stock = excluded.stock, is_featured = excluded.is_featured, sort = excluded.sort, tips = excluded.tips;

-- Recettes
insert into public.recipes (id, slug, title, intro, image, duration_min, servings, difficulty, ingredients, steps, product_slugs)
values ('r-poulet-roti', 'poulet-roti-aux-herbes', '{"fr":"Poulet rôti aux herbes du Cap Bon","ar":"دجاج مشوي بأعشاب الوطن القبلي"}'::jsonb, '{"fr":"Le dimanche à la maison : un poulet fermier, du thym, du citron, et le four qui fait le reste.","ar":"الأحد في البيت: دجاج بلدي، زعتر، ليمون، والفرن يقوم بالباقي."}'::jsonb, '/images/recipes/recette-poulet-roti.jpg', 90, 4, 1, '{"fr":["1 poulet fermier entier","1 citron","4 gousses d’ail","Thym et romarin","3 c. à s. d’huile d’olive","Sel, poivre","1 kg de pommes de terre"],"ar":["دجاجة بلدية كاملة","ليمونة","4 فصوص ثوم","زعتر وإكليل الجبل","3 ملاعق كبيرة زيت زيتون","ملح وفلفل","1 كغ بطاطا"]}'::jsonb, '{"fr":["Préchauffez le four à 200 °C. Sortez le poulet 30 minutes avant.","Frottez-le d’huile d’olive, de sel et de poivre. Glissez le citron coupé et l’ail dans le ventre.","Posez-le sur les pommes de terre coupées en quartiers, parsemez d’herbes.","Enfournez 1 h 15. Arrosez toutes les 20 minutes avec le jus.","Laissez reposer 10 minutes sous un torchon avant de découper."],"ar":["سخّن الفرن على 200 درجة. أخرج الدجاجة قبل 30 دقيقة.","ادهنها بزيت الزيتون والملح والفلفل. ضع الليمون المقطّع والثوم داخلها.","ضعها فوق البطاطا المقطّعة أرباعاً وانثر الأعشاب.","اطهِها ساعة وربع. اسقها بالمرق كل 20 دقيقة.","اتركها ترتاح 10 دقائق تحت منشفة قبل التقطيع."]}'::jsonb, array['poulet-fermier-entier']::text[])
on conflict (id) do update set slug = excluded.slug, title = excluded.title, intro = excluded.intro, image = excluded.image, duration_min = excluded.duration_min, servings = excluded.servings, difficulty = excluded.difficulty, ingredients = excluded.ingredients, steps = excluded.steps, product_slugs = excluded.product_slugs;
insert into public.recipes (id, slug, title, intro, image, duration_min, servings, difficulty, ingredients, steps, product_slugs)
values ('r-tajine', 'tajine-de-poulet-aux-olives', '{"fr":"Tajine de poulet aux olives et au citron confit","ar":"طاجين دجاج بالزيتون والليمون المصبّر"}'::jsonb, '{"fr":"Des cuisses qui mijotent doucement, des olives, un citron confit : le plat qui parfume toute la maison.","ar":"أفخاذ تُطهى على نار هادئة، زيتون وليمون مصبّر: الطبق الذي يعطّر البيت كله."}'::jsonb, '/images/recipes/recette-tajine.jpg', 75, 4, 2, '{"fr":["1 kg de cuisses de poulet","2 oignons","1 citron confit","150 g d’olives vertes","1 c. à c. de curcuma","1 c. à c. de gingembre","Coriandre fraîche","Huile d’olive"],"ar":["1 كغ أفخاذ دجاج","بصلتان","ليمونة مصبّرة","150 غ زيتون أخضر","ملعقة صغيرة كركم","ملعقة صغيرة زنجبيل","كزبرة طازجة","زيت زيتون"]}'::jsonb, '{"fr":["Faites dorer les cuisses dans l’huile d’olive, réservez.","Faites fondre les oignons émincés avec les épices.","Remettez le poulet, couvrez d’eau à mi-hauteur, laissez mijoter 45 minutes à couvert.","Ajoutez les olives et le citron confit en morceaux, poursuivez 10 minutes.","Parsemez de coriandre et servez avec du pain ou de la semoule."],"ar":["حمّر الأفخاذ في زيت الزيتون ثم ضعها جانباً.","اطهُ البصل المقطّع مع التوابل حتى يذبل.","أعد الدجاج وغطّه بالماء إلى النصف واتركه يغلي 45 دقيقة مغطّى.","أضف الزيتون وقطع الليمون المصبّر واطهُ 10 دقائق أخرى.","انثر الكزبرة وقدّمه مع الخبز أو السميد."]}'::jsonb, array['cuisses-de-poulet']::text[])
on conflict (id) do update set slug = excluded.slug, title = excluded.title, intro = excluded.intro, image = excluded.image, duration_min = excluded.duration_min, servings = excluded.servings, difficulty = excluded.difficulty, ingredients = excluded.ingredients, steps = excluded.steps, product_slugs = excluded.product_slugs;
insert into public.recipes (id, slug, title, intro, image, duration_min, servings, difficulty, ingredients, steps, product_slugs)
values ('r-brochettes', 'brochettes-grillees-harissa', '{"fr":"Brochettes grillées, harissa et citron","ar":"أسياخ مشوية بالهريسة والليمون"}'::jsonb, '{"fr":"La braise du soir, les brochettes déjà marinées, une salade mechouia à côté.","ar":"جمر المساء، أسياخ متبّلة مسبقاً، وسلطة مشوية إلى جانبها."}'::jsonb, '/images/recipes/recette-brochettes.jpg', 25, 4, 1, '{"fr":["1 kg de brochettes de poulet marinées","1 c. à s. de harissa","1 citron","Pain tabouna","Salade mechouia"],"ar":["1 كغ أسياخ دجاج متبّلة","ملعقة كبيرة هريسة","ليمونة","خبز طابونة","سلطة مشوية"]}'::jsonb, '{"fr":["Sortez les brochettes 20 minutes avant la cuisson.","Sur une braise bien grise, grillez 4 minutes par face.","Mélangez la harissa avec le jus de citron, badigeonnez en fin de cuisson.","Servez dans le pain tabouna avec la mechouia."],"ar":["أخرج الأسياخ قبل الطهي بـ20 دقيقة.","على جمر رمادي جيد، اشوِ 4 دقائق لكل جهة.","اخلط الهريسة مع عصير الليمون وادهن بها في نهاية الطهي.","قدّمها في خبز الطابونة مع السلطة المشوية."]}'::jsonb, array['brochettes-de-poulet-marinees']::text[])
on conflict (id) do update set slug = excluded.slug, title = excluded.title, intro = excluded.intro, image = excluded.image, duration_min = excluded.duration_min, servings = excluded.servings, difficulty = excluded.difficulty, ingredients = excluded.ingredients, steps = excluded.steps, product_slugs = excluded.product_slugs;
insert into public.recipes (id, slug, title, intro, image, duration_min, servings, difficulty, ingredients, steps, product_slugs)
values ('r-ojja', 'ojja-aux-merguez', '{"fr":"Ojja aux merguez et aux œufs fermiers","ar":"عجّة بالمرقاز والبيض البلدي"}'::jsonb, '{"fr":"Le plat du soir en 20 minutes : tomates, merguez, poivrons, et les œufs qui prennent dessus.","ar":"طبق المساء في 20 دقيقة: طماطم، مرقاز، فلفل، والبيض يستوي فوقها."}'::jsonb, '/images/recipes/recette-omelette.jpg', 20, 2, 1, '{"fr":["4 œufs fermiers","250 g de merguez de volaille","3 tomates","1 poivron vert","2 gousses d’ail","1 c. à s. de concentré de tomate","Harissa, carvi, sel"],"ar":["4 بيضات بلدية","250 غ مرقاز دواجن","3 طماطم","فلفلة خضراء","فصان ثوم","ملعقة كبيرة معجون طماطم","هريسة، كروية، ملح"]}'::jsonb, '{"fr":["Faites revenir les merguez coupées en tronçons, réservez.","Dans la même poêle, faites fondre l’ail, le poivron et le concentré, puis les tomates en dés. Laissez réduire 10 minutes.","Remettez les merguez, cassez les œufs par-dessus, couvrez 3 minutes.","Servez aussitôt avec du pain."],"ar":["حمّر المرقاز المقطّع ثم ضعه جانباً.","في نفس المقلاة اطهُ الثوم والفلفل والمعجون ثم الطماطم المقطّعة. اتركها تتكاثف 10 دقائق.","أعد المرقاز واكسر البيض فوقه وغطّه 3 دقائق.","قدّمها فوراً مع الخبز."]}'::jsonb, array['oeufs-fermiers-x6', 'merguez-de-volaille']::text[])
on conflict (id) do update set slug = excluded.slug, title = excluded.title, intro = excluded.intro, image = excluded.image, duration_min = excluded.duration_min, servings = excluded.servings, difficulty = excluded.difficulty, ingredients = excluded.ingredients, steps = excluded.steps, product_slugs = excluded.product_slugs;

-- Zones de livraison
insert into public.delivery_zones (id, name, areas, fee, free_from, lead_days, active, sort)
values ('z-korba', '{"fr":"Korba et alentours","ar":"قربة وضواحيها"}'::jsonb, '{"fr":"Korba, Tazerka, Diar El Hojjaj, Bou Argoub","ar":"قربة، تازركة، ديار الحجاج، بوعرقوب"}'::jsonb, 3, 60, 0, true, 1)
on conflict (id) do update set name = excluded.name, areas = excluded.areas, fee = excluded.fee, free_from = excluded.free_from, lead_days = excluded.lead_days, active = excluded.active, sort = excluded.sort;
insert into public.delivery_zones (id, name, areas, fee, free_from, lead_days, active, sort)
values ('z-cap-bon', '{"fr":"Cap Bon nord","ar":"شمال الوطن القبلي"}'::jsonb, '{"fr":"Menzel Temime, Kélibia, Béni Khalled, Menzel Bouzelfa","ar":"منزل تميم، قليبية، بني خلاد، منزل بوزلفة"}'::jsonb, 5, 100, 1, true, 2)
on conflict (id) do update set name = excluded.name, areas = excluded.areas, fee = excluded.fee, free_from = excluded.free_from, lead_days = excluded.lead_days, active = excluded.active, sort = excluded.sort;
insert into public.delivery_zones (id, name, areas, fee, free_from, lead_days, active, sort)
values ('z-nabeul', '{"fr":"Nabeul et Hammamet","ar":"نابل والحمامات"}'::jsonb, '{"fr":"Nabeul, Dar Chaabane, Hammamet, Grombalia","ar":"نابل، دار شعبان، الحمامات، قرمبالية"}'::jsonb, 7, 150, 1, true, 3)
on conflict (id) do update set name = excluded.name, areas = excluded.areas, fee = excluded.fee, free_from = excluded.free_from, lead_days = excluded.lead_days, active = excluded.active, sort = excluded.sort;
insert into public.delivery_zones (id, name, areas, fee, free_from, lead_days, active, sort)
values ('z-tunis', '{"fr":"Grand Tunis","ar":"تونس الكبرى"}'::jsonb, '{"fr":"Tunis, La Marsa, Ariana, Ben Arous, Le Bardo","ar":"تونس، المرسى، أريانة، بن عروس، باردو"}'::jsonb, 12, 250, 1, true, 4)
on conflict (id) do update set name = excluded.name, areas = excluded.areas, fee = excluded.fee, free_from = excluded.free_from, lead_days = excluded.lead_days, active = excluded.active, sort = excluded.sort;

-- Créneaux de livraison
insert into public.delivery_slots (id, label, slot_from, slot_to, days, active, sort)
values ('s-matin', '{"fr":"Matin","ar":"صباحاً"}'::jsonb, '09:00', '12:00', array[1, 2, 3, 4, 5, 6]::integer[], true, 1)
on conflict (id) do update set label = excluded.label, slot_from = excluded.slot_from, slot_to = excluded.slot_to, days = excluded.days, active = excluded.active, sort = excluded.sort;
insert into public.delivery_slots (id, label, slot_from, slot_to, days, active, sort)
values ('s-midi', '{"fr":"Début d’après-midi","ar":"بداية بعد الظهر"}'::jsonb, '13:00', '16:00', array[1, 2, 3, 4, 5, 6]::integer[], true, 2)
on conflict (id) do update set label = excluded.label, slot_from = excluded.slot_from, slot_to = excluded.slot_to, days = excluded.days, active = excluded.active, sort = excluded.sort;
insert into public.delivery_slots (id, label, slot_from, slot_to, days, active, sort)
values ('s-soir', '{"fr":"Fin de journée","ar":"آخر النهار"}'::jsonb, '16:00', '19:00', array[1, 2, 3, 4, 5, 6]::integer[], true, 3)
on conflict (id) do update set label = excluded.label, slot_from = excluded.slot_from, slot_to = excluded.slot_to, days = excluded.days, active = excluded.active, sort = excluded.sort;

-- Réglages (une seule ligne, id = 1)
insert into public.settings (id, shop_open, announcement, min_order, max_days_ahead, cutoff_time, closed_days)
values (1, true, '{"fr":"","ar":""}'::jsonb, 20, 6, '18:00', array[0]::integer[])
on conflict (id) do update set shop_open = excluded.shop_open, announcement = excluded.announcement, min_order = excluded.min_order, max_days_ahead = excluded.max_days_ahead, cutoff_time = excluded.cutoff_time, closed_days = excluded.closed_days;

commit;
