import type { Category, DeliverySlot, DeliveryZone, Offer, Product, Recipe, Settings } from './types';

/**
 * Jeu de données de départ. Il sert :
 * - à construire le site statique (pages produits, recettes) ;
 * - au mode démo, quand aucune base Supabase n'est configurée ;
 * - au script seed.sql pour remplir la base la première fois.
 * Les images pointent vers /images/products/… et /images/recipes/… du site.
 */

export const categories: Category[] = [
  {
    id: 'cat-volailles',
    slug: 'volailles-entieres',
    name: { fr: 'Volailles entières', ar: 'دواجن كاملة' },
    description: {
      fr: 'Poulets et poules élevés en plein air, abattus le matin de votre livraison.',
      ar: 'دجاج بلدي مرباة في الهواء الطلق، تُذبح صباح يوم التوصيل.',
    },
    image: '/images/products/poulet-entier.jpg',
    sort: 1,
  },
  {
    id: 'cat-decoupes',
    slug: 'decoupes',
    name: { fr: 'Découpes de poulet', ar: 'قطع الدجاج' },
    description: {
      fr: 'Cuisses, escalopes, ailes et pilons, découpés à la demande.',
      ar: 'أفخاذ، إسكالوب، أجنحة وسيقان، تُقطّع عند الطلب.',
    },
    image: '/images/products/escalope-poulet.jpg',
    sort: 2,
  },
  {
    id: 'cat-dinde',
    slug: 'dinde',
    name: { fr: 'Dinde', ar: 'ديك رومي' },
    description: {
      fr: 'Escalopes et filets de dinde, tendres et maigres.',
      ar: 'إسكالوب وفيليه ديك رومي، طري وقليل الدهن.',
    },
    image: '/images/products/dinde-escalope.jpg',
    sort: 3,
  },
  {
    id: 'cat-oeufs',
    slug: 'oeufs',
    name: { fr: 'Œufs fermiers', ar: 'بيض بلدي' },
    description: {
      fr: 'Ramassés chaque matin. Jaune orangé, coquille solide.',
      ar: 'يُجمع كل صباح. صفار برتقالي وقشرة صلبة.',
    },
    image: '/images/products/oeufs.jpg',
    sort: 4,
  },
  {
    id: 'cat-charcuterie',
    slug: 'charcuterie',
    name: { fr: 'Charcuterie de volaille', ar: 'شاركوتري الدواجن' },
    description: {
      fr: 'Merguez, saucisses, jambon et salami de volaille, faits à la ferme.',
      ar: 'مرقاز، سجق، جامبون وسلامي دواجن، مصنوعة في المزرعة.',
    },
    image: '/images/products/charcuterie-volaille.jpg',
    sort: 5,
  },
  {
    id: 'cat-marines',
    slug: 'marines',
    name: { fr: 'Marinés et prêts à cuire', ar: 'متبّل وجاهز للطهي' },
    description: {
      fr: 'Brochettes, cuisses marinées et nuggets maison. Il ne reste qu’à cuire.',
      ar: 'أسياخ، أفخاذ متبّلة وناغتس منزلية. ما عليك إلا الطهي.',
    },
    image: '/images/products/brochettes.jpg',
    sort: 6,
  },
];

const P = (p: Product): Product => p;

export const products: Product[] = [
  P({
    id: 'p-poulet-fermier',
    slug: 'poulet-fermier-entier',
    category_id: 'cat-volailles',
    name: { fr: 'Poulet fermier entier', ar: 'دجاج بلدي كامل' },
    short: { fr: 'Élevé 90 jours en plein air, environ 1,7 kg', ar: 'مرباة 90 يوماً في الهواء الطلق، حوالي 1.7 كغ' },
    description: {
      fr: 'Notre poulet fermier grandit lentement, dehors, nourri au grain. Chair ferme et goûteuse, peau dorée à la cuisson. Livré entier, vidé et prêt à rôtir. Le prix est ajusté au poids réel à la pesée.',
      ar: 'ينمو دجاجنا البلدي ببطء في الهواء الطلق ويتغذى على الحبوب. لحم متماسك ولذيذ وجلد ذهبي عند الطهي. يُسلَّم كاملاً ومنظفاً وجاهزاً للشوي. يُعدَّل السعر حسب الوزن الحقيقي عند الوزن.',
    },
    images: ['/images/products/poulet-entier.jpg'],
    pricing: { mode: 'per_kg_estimated', price_per_kg: 14.9, est_weight_kg: 1.7, min_weight_kg: 1.4, max_weight_kg: 2.1, max_qty: 10 },
    badges: ['fermier', 'best'],
    stock: 'en_stock',
    is_featured: true,
    sort: 1,
    tips: { fr: 'Se conserve 3 jours au réfrigérateur. Sortez-le 30 min avant de le cuire.', ar: 'يُحفظ 3 أيام في الثلاجة. أخرجه قبل الطهي بـ30 دقيقة.' },
  }),
  P({
    id: 'p-poulet-petit',
    slug: 'petit-poulet-fermier',
    category_id: 'cat-volailles',
    name: { fr: 'Petit poulet fermier', ar: 'دجاج بلدي صغير' },
    short: { fr: 'Pour 2 personnes, environ 1,2 kg', ar: 'لشخصين، حوالي 1.2 كغ' },
    description: {
      fr: 'Le même poulet fermier, en plus petit format. Parfait pour un dîner à deux ou un poulet rôti du dimanche sans restes.',
      ar: 'نفس الدجاج البلدي بحجم أصغر. مثالي لعشاء لشخصين أو دجاج مشوي دون بقايا.',
    },
    images: ['/images/products/poulet-entier.jpg'],
    pricing: { mode: 'per_kg_estimated', price_per_kg: 14.9, est_weight_kg: 1.2, min_weight_kg: 1.0, max_weight_kg: 1.4, max_qty: 10 },
    badges: ['fermier'],
    stock: 'en_stock',
    is_featured: false,
    sort: 2,
  }),
  P({
    id: 'p-poule',
    slug: 'poule-fermiere',
    category_id: 'cat-volailles',
    name: { fr: 'Poule fermière', ar: 'دجاجة بلدية' },
    short: { fr: 'Pour le couscous et les bouillons, environ 2 kg', ar: 'للكسكسي والمرق، حوالي 2 كغ' },
    description: {
      fr: 'La poule de réforme, celle de nos grands-mères. Chair plus ferme, goût profond : c’est elle qui fait le vrai bouillon du couscous et de la chorba.',
      ar: 'دجاجة بلدية كبيرة كما كانت جداتنا تطهوها. لحم أكثر تماسكاً وطعم عميق: هي سر مرق الكسكسي والشوربة.',
    },
    images: ['/images/products/poules-plein-air.jpg'],
    pricing: { mode: 'per_kg_estimated', price_per_kg: 12.5, est_weight_kg: 2.0, min_weight_kg: 1.7, max_weight_kg: 2.5, max_qty: 6 },
    badges: ['fermier'],
    stock: 'en_stock',
    is_featured: false,
    sort: 3,
  }),
  P({
    id: 'p-cuisses',
    slug: 'cuisses-de-poulet',
    category_id: 'cat-decoupes',
    name: { fr: 'Cuisses de poulet', ar: 'أفخاذ دجاج' },
    short: { fr: 'Cuisses entières, avec peau', ar: 'أفخاذ كاملة، مع الجلد' },
    description: {
      fr: 'Cuisses entières de poulet fermier, haut et pilon attachés. La pièce préférée pour le four, la braise et le tajine.',
      ar: 'أفخاذ دجاج بلدي كاملة، الفخذ والساق معاً. القطعة المفضلة للفرن والشواء والطاجين.',
    },
    images: ['/images/products/cuisses-poulet.jpg'],
    pricing: { mode: 'per_kg', price_per_kg: 15.9, step_kg: 0.5, min_kg: 0.5, max_kg: 10 },
    badges: ['best'],
    stock: 'en_stock',
    is_featured: true,
    sort: 1,
  }),
  P({
    id: 'p-escalopes',
    slug: 'escalopes-de-poulet',
    category_id: 'cat-decoupes',
    name: { fr: 'Escalopes de poulet', ar: 'إسكالوب دجاج' },
    short: { fr: 'Blanc de poulet tranché fin', ar: 'صدر دجاج مقطّع رقيق' },
    description: {
      fr: 'Blancs de poulet fermier tranchés en escalopes régulières. Sans os, sans peau. Pour les paniers, les salades et les plats rapides de la semaine.',
      ar: 'صدور دجاج بلدي مقطّعة إلى شرائح منتظمة. بدون عظم ولا جلد. للبانيه والسلطات وأطباق الأسبوع السريعة.',
    },
    images: ['/images/products/escalope-poulet.jpg'],
    pricing: { mode: 'per_kg', price_per_kg: 22.9, step_kg: 0.25, min_kg: 0.5, max_kg: 10 },
    badges: ['best'],
    stock: 'en_stock',
    is_featured: true,
    sort: 2,
  }),
  P({
    id: 'p-ailes',
    slug: 'ailes-de-poulet',
    category_id: 'cat-decoupes',
    name: { fr: 'Ailes de poulet', ar: 'أجنحة دجاج' },
    short: { fr: 'Pour la braise et le four', ar: 'للشواء والفرن' },
    description: {
      fr: 'Ailes entières, charnues, idéales grillées avec un peu de harissa et de citron.',
      ar: 'أجنحة كاملة ولحيمة، مثالية مشوية مع قليل من الهريسة والليمون.',
    },
    images: ['/images/products/ailes-poulet.jpg'],
    pricing: { mode: 'per_kg', price_per_kg: 11.9, step_kg: 0.5, min_kg: 0.5, max_kg: 10 },
    badges: [],
    stock: 'en_stock',
    is_featured: false,
    sort: 3,
  }),
  P({
    id: 'p-pilons',
    slug: 'pilons-de-poulet',
    category_id: 'cat-decoupes',
    name: { fr: 'Pilons de poulet', ar: 'سيقان دجاج' },
    short: { fr: 'Les préférés des enfants', ar: 'المفضلة عند الأطفال' },
    description: {
      fr: 'Pilons de poulet fermier, faciles à tenir, faciles à cuire. Au four, en 35 minutes, avec des pommes de terre.',
      ar: 'سيقان دجاج بلدي، سهلة الإمساك وسهلة الطهي. في الفرن خلال 35 دقيقة مع البطاطا.',
    },
    images: ['/images/products/pilons-poulet.jpg'],
    pricing: { mode: 'per_kg', price_per_kg: 14.5, step_kg: 0.5, min_kg: 0.5, max_kg: 10 },
    badges: [],
    stock: 'en_stock',
    is_featured: false,
    sort: 4,
  }),
  P({
    id: 'p-dinde-escalope',
    slug: 'escalopes-de-dinde',
    category_id: 'cat-dinde',
    name: { fr: 'Escalopes de dinde', ar: 'إسكالوب ديك رومي' },
    short: { fr: 'Maigres et tendres', ar: 'قليلة الدهن وطرية' },
    description: {
      fr: 'Escalopes de dinde tranchées le jour même. Très maigres, elles conviennent aux grillades et aux régimes.',
      ar: 'إسكالوب ديك رومي مقطّع في نفس اليوم. قليل الدهن جداً، مناسب للشواء والحمية.',
    },
    images: ['/images/products/dinde-escalope.jpg'],
    pricing: { mode: 'per_kg', price_per_kg: 23.9, step_kg: 0.25, min_kg: 0.5, max_kg: 10 },
    badges: [],
    stock: 'en_stock',
    is_featured: false,
    sort: 1,
  }),
  P({
    id: 'p-dinde-filet',
    slug: 'filet-de-dinde',
    category_id: 'cat-dinde',
    name: { fr: 'Filet de dinde entier', ar: 'فيليه ديك رومي كامل' },
    short: { fr: 'Pour rôtir ou farcir', ar: 'للشوي أو الحشو' },
    description: {
      fr: 'Le filet entier, à rôtir doucement ou à farcir pour les grandes tablées.',
      ar: 'الفيليه كاملاً، يُشوى على نار هادئة أو يُحشى للولائم.',
    },
    images: ['/images/products/dinde-escalope.jpg'],
    pricing: { mode: 'per_kg', price_per_kg: 21.9, step_kg: 0.5, min_kg: 1, max_kg: 10 },
    badges: [],
    stock: 'bientot',
    is_featured: false,
    sort: 2,
  }),
  P({
    id: 'p-oeufs-6',
    slug: 'oeufs-fermiers-x6',
    category_id: 'cat-oeufs',
    name: { fr: 'Œufs fermiers, boîte de 6', ar: 'بيض بلدي، علبة 6' },
    short: { fr: 'Ramassés ce matin', ar: 'جُمع هذا الصباح' },
    description: {
      fr: 'Six œufs de poules élevées en plein air, ramassés le matin. Jaune orangé, blanc qui se tient.',
      ar: 'ست بيضات من دجاج مرباة في الهواء الطلق، جُمعت صباحاً. صفار برتقالي وبياض متماسك.',
    },
    images: ['/images/products/oeufs.jpg'],
    pricing: { mode: 'per_piece', price: 3.6, max_qty: 20 },
    badges: ['fermier'],
    stock: 'en_stock',
    is_featured: true,
    sort: 1,
    tips: { fr: 'Se conservent 3 semaines au frais. Ne les lavez pas avant de les ranger.', ar: 'يُحفظ 3 أسابيع في البرودة. لا تغسلها قبل التخزين.' },
  }),
  P({
    id: 'p-oeufs-12',
    slug: 'oeufs-fermiers-x12',
    category_id: 'cat-oeufs',
    name: { fr: 'Œufs fermiers, boîte de 12', ar: 'بيض بلدي، علبة 12' },
    short: { fr: 'La boîte de la semaine', ar: 'علبة الأسبوع' },
    description: {
      fr: 'Douze œufs fermiers dans une boîte en carton recyclable.',
      ar: 'اثنتا عشرة بيضة بلدية في علبة كرتون قابلة لإعادة التدوير.',
    },
    images: ['/images/products/oeufs.jpg'],
    pricing: { mode: 'per_piece', price: 6.9, max_qty: 20 },
    badges: ['fermier', 'best'],
    stock: 'en_stock',
    is_featured: false,
    sort: 2,
  }),
  P({
    id: 'p-oeufs-30',
    slug: 'oeufs-fermiers-plateau-30',
    category_id: 'cat-oeufs',
    name: { fr: 'Œufs fermiers, plateau de 30', ar: 'بيض بلدي، صينية 30' },
    short: { fr: 'Pour les familles et les restaurants', ar: 'للعائلات والمطاعم' },
    description: {
      fr: 'Le plateau de trente, le meilleur prix à l’œuf.',
      ar: 'صينية الثلاثين، أفضل سعر للبيضة.',
    },
    images: ['/images/products/oeufs.jpg'],
    pricing: { mode: 'per_piece', price: 15.9, max_qty: 10 },
    badges: ['fermier'],
    stock: 'en_stock',
    is_featured: false,
    sort: 3,
  }),
  P({
    id: 'p-merguez',
    slug: 'merguez-de-volaille',
    category_id: 'cat-charcuterie',
    name: { fr: 'Merguez de volaille', ar: 'مرقاز دواجن' },
    short: { fr: 'Épicées comme il faut', ar: 'متبّلة كما يجب' },
    description: {
      fr: 'Merguez de poulet et de dinde, harissa et épices de Nabeul. Faites à la ferme, sans colorant. Environ 12 merguez au kilo.',
      ar: 'مرقاز دجاج وديك رومي، هريسة وتوابل نابل. مصنوع في المزرعة دون ملوّنات. حوالي 12 مرقازة في الكيلو.',
    },
    images: ['/images/products/merguez.jpg'],
    pricing: { mode: 'per_kg', price_per_kg: 19.9, step_kg: 0.5, min_kg: 0.5, max_kg: 10 },
    badges: ['best'],
    stock: 'en_stock',
    is_featured: true,
    sort: 1,
  }),
  P({
    id: 'p-saucisses',
    slug: 'saucisses-de-poulet',
    category_id: 'cat-charcuterie',
    name: { fr: 'Saucisses de poulet', ar: 'سجق دجاج' },
    short: { fr: 'Nature, aux herbes', ar: 'طبيعي بالأعشاب' },
    description: {
      fr: 'Saucisses de poulet aux herbes fraîches, douces, appréciées des enfants.',
      ar: 'سجق دجاج بالأعشاب الطازجة، خفيف التوابل، يحبه الأطفال.',
    },
    images: ['/images/products/saucisses-volaille.jpg'],
    pricing: { mode: 'per_kg', price_per_kg: 18.5, step_kg: 0.5, min_kg: 0.5, max_kg: 10 },
    badges: [],
    stock: 'en_stock',
    is_featured: false,
    sort: 2,
  }),
  P({
    id: 'p-jambon',
    slug: 'jambon-de-dinde-tranche',
    category_id: 'cat-charcuterie',
    name: { fr: 'Jambon de dinde tranché, 200 g', ar: 'جامبون ديك رومي مقطّع، 200 غ' },
    short: { fr: 'Pour les sandwichs du matin', ar: 'لساندويتشات الصباح' },
    description: {
      fr: 'Jambon de dinde cuit à la ferme, tranché fin, en barquette de 200 g.',
      ar: 'جامبون ديك رومي مطبوخ في المزرعة، مقطّع رقيقاً، في علبة 200 غ.',
    },
    images: ['/images/products/charcuterie-volaille.jpg'],
    pricing: { mode: 'per_piece', price: 6.9, max_qty: 20 },
    badges: [],
    stock: 'en_stock',
    is_featured: false,
    sort: 3,
  }),
  P({
    id: 'p-salami',
    slug: 'salami-de-volaille',
    category_id: 'cat-charcuterie',
    name: { fr: 'Salami de volaille, 200 g', ar: 'سلامي دواجن، 200 غ' },
    short: { fr: 'Tranché, prêt à servir', ar: 'مقطّع وجاهز للتقديم' },
    description: {
      fr: 'Salami de volaille doux, tranché, en barquette de 200 g.',
      ar: 'سلامي دواجن خفيف، مقطّع، في علبة 200 غ.',
    },
    images: ['/images/products/charcuterie-volaille.jpg'],
    pricing: { mode: 'per_piece', price: 5.9, max_qty: 20 },
    badges: ['nouveau'],
    stock: 'en_stock',
    is_featured: false,
    sort: 4,
  }),
  P({
    id: 'p-brochettes',
    slug: 'brochettes-de-poulet-marinees',
    category_id: 'cat-marines',
    name: { fr: 'Brochettes de poulet marinées', ar: 'أسياخ دجاج متبّلة' },
    short: { fr: 'Citron, ail, épices', ar: 'ليمون، ثوم، توابل' },
    description: {
      fr: 'Cubes de blanc de poulet marinés au citron, à l’ail et aux épices, sur pique en bois. Sur la braise en 10 minutes.',
      ar: 'مكعبات صدر دجاج متبّلة بالليمون والثوم والتوابل على أسياخ خشبية. على الجمر خلال 10 دقائق.',
    },
    images: ['/images/products/brochettes.jpg'],
    pricing: { mode: 'per_kg', price_per_kg: 24.9, step_kg: 0.5, min_kg: 0.5, max_kg: 10 },
    badges: ['best'],
    stock: 'en_stock',
    is_featured: true,
    sort: 1,
  }),
  P({
    id: 'p-cuisses-marinees',
    slug: 'cuisses-marinees',
    category_id: 'cat-marines',
    name: { fr: 'Cuisses marinées', ar: 'أفخاذ متبّلة' },
    short: { fr: 'Prêtes pour le four', ar: 'جاهزة للفرن' },
    description: {
      fr: 'Cuisses de poulet fermier marinées la veille dans notre mélange maison. Au four, 45 minutes, c’est prêt.',
      ar: 'أفخاذ دجاج بلدي متبّلة من الليلة السابقة بخلطتنا المنزلية. 45 دقيقة في الفرن وتكون جاهزة.',
    },
    images: ['/images/products/cuisses-poulet.jpg'],
    pricing: { mode: 'per_kg', price_per_kg: 17.9, step_kg: 0.5, min_kg: 0.5, max_kg: 10 },
    badges: [],
    stock: 'en_stock',
    is_featured: false,
    sort: 2,
  }),
  P({
    id: 'p-nuggets',
    slug: 'nuggets-maison-500g',
    category_id: 'cat-marines',
    name: { fr: 'Nuggets maison, 500 g', ar: 'ناغتس منزلية، 500 غ' },
    short: { fr: 'Du vrai blanc de poulet', ar: 'من صدر دجاج حقيقي' },
    description: {
      fr: 'Nuggets faits avec du vrai blanc de poulet fermier, panés à la maison. Sachet de 500 g, environ 20 pièces.',
      ar: 'ناغتس مصنوعة من صدر دجاج بلدي حقيقي، مغلّفة بالبقسماط في المزرعة. كيس 500 غ، حوالي 20 قطعة.',
    },
    images: ['/images/products/escalope-poulet.jpg'],
    pricing: { mode: 'per_piece', price: 12.9, max_qty: 20 },
    badges: ['nouveau'],
    stock: 'en_stock',
    is_featured: false,
    sort: 3,
  }),
];

export const recipes: Recipe[] = [
  {
    id: 'r-poulet-roti',
    slug: 'poulet-roti-aux-herbes',
    title: { fr: 'Poulet rôti aux herbes du Cap Bon', ar: 'دجاج مشوي بأعشاب الوطن القبلي' },
    intro: {
      fr: 'Le dimanche à la maison : un poulet fermier, du thym, du citron, et le four qui fait le reste.',
      ar: 'الأحد في البيت: دجاج بلدي، زعتر، ليمون، والفرن يقوم بالباقي.',
    },
    image: '/images/recipes/recette-poulet-roti.jpg',
    duration_min: 90,
    servings: 4,
    difficulty: 1,
    ingredients: {
      fr: ['1 poulet fermier entier', '1 citron', '4 gousses d’ail', 'Thym et romarin', '3 c. à s. d’huile d’olive', 'Sel, poivre', '1 kg de pommes de terre'],
      ar: ['دجاجة بلدية كاملة', 'ليمونة', '4 فصوص ثوم', 'زعتر وإكليل الجبل', '3 ملاعق كبيرة زيت زيتون', 'ملح وفلفل', '1 كغ بطاطا'],
    },
    steps: {
      fr: [
        'Préchauffez le four à 200 °C. Sortez le poulet 30 minutes avant.',
        'Frottez-le d’huile d’olive, de sel et de poivre. Glissez le citron coupé et l’ail dans le ventre.',
        'Posez-le sur les pommes de terre coupées en quartiers, parsemez d’herbes.',
        'Enfournez 1 h 15. Arrosez toutes les 20 minutes avec le jus.',
        'Laissez reposer 10 minutes sous un torchon avant de découper.',
      ],
      ar: [
        'سخّن الفرن على 200 درجة. أخرج الدجاجة قبل 30 دقيقة.',
        'ادهنها بزيت الزيتون والملح والفلفل. ضع الليمون المقطّع والثوم داخلها.',
        'ضعها فوق البطاطا المقطّعة أرباعاً وانثر الأعشاب.',
        'اطهِها ساعة وربع. اسقها بالمرق كل 20 دقيقة.',
        'اتركها ترتاح 10 دقائق تحت منشفة قبل التقطيع.',
      ],
    },
    product_slugs: ['poulet-fermier-entier'],
  },
  {
    id: 'r-tajine',
    slug: 'tajine-de-poulet-aux-olives',
    title: { fr: 'Tajine de poulet aux olives et au citron confit', ar: 'طاجين دجاج بالزيتون والليمون المصبّر' },
    intro: {
      fr: 'Des cuisses qui mijotent doucement, des olives, un citron confit : le plat qui parfume toute la maison.',
      ar: 'أفخاذ تُطهى على نار هادئة، زيتون وليمون مصبّر: الطبق الذي يعطّر البيت كله.',
    },
    image: '/images/recipes/recette-tajine.jpg',
    duration_min: 75,
    servings: 4,
    difficulty: 2,
    ingredients: {
      fr: ['1 kg de cuisses de poulet', '2 oignons', '1 citron confit', '150 g d’olives vertes', '1 c. à c. de curcuma', '1 c. à c. de gingembre', 'Coriandre fraîche', 'Huile d’olive'],
      ar: ['1 كغ أفخاذ دجاج', 'بصلتان', 'ليمونة مصبّرة', '150 غ زيتون أخضر', 'ملعقة صغيرة كركم', 'ملعقة صغيرة زنجبيل', 'كزبرة طازجة', 'زيت زيتون'],
    },
    steps: {
      fr: [
        'Faites dorer les cuisses dans l’huile d’olive, réservez.',
        'Faites fondre les oignons émincés avec les épices.',
        'Remettez le poulet, couvrez d’eau à mi-hauteur, laissez mijoter 45 minutes à couvert.',
        'Ajoutez les olives et le citron confit en morceaux, poursuivez 10 minutes.',
        'Parsemez de coriandre et servez avec du pain ou de la semoule.',
      ],
      ar: [
        'حمّر الأفخاذ في زيت الزيتون ثم ضعها جانباً.',
        'اطهُ البصل المقطّع مع التوابل حتى يذبل.',
        'أعد الدجاج وغطّه بالماء إلى النصف واتركه يغلي 45 دقيقة مغطّى.',
        'أضف الزيتون وقطع الليمون المصبّر واطهُ 10 دقائق أخرى.',
        'انثر الكزبرة وقدّمه مع الخبز أو السميد.',
      ],
    },
    product_slugs: ['cuisses-de-poulet'],
  },
  {
    id: 'r-brochettes',
    slug: 'brochettes-grillees-harissa',
    title: { fr: 'Brochettes grillées, harissa et citron', ar: 'أسياخ مشوية بالهريسة والليمون' },
    intro: {
      fr: 'La braise du soir, les brochettes déjà marinées, une salade mechouia à côté.',
      ar: 'جمر المساء، أسياخ متبّلة مسبقاً، وسلطة مشوية إلى جانبها.',
    },
    image: '/images/recipes/recette-brochettes.jpg',
    duration_min: 25,
    servings: 4,
    difficulty: 1,
    ingredients: {
      fr: ['1 kg de brochettes de poulet marinées', '1 c. à s. de harissa', '1 citron', 'Pain tabouna', 'Salade mechouia'],
      ar: ['1 كغ أسياخ دجاج متبّلة', 'ملعقة كبيرة هريسة', 'ليمونة', 'خبز طابونة', 'سلطة مشوية'],
    },
    steps: {
      fr: [
        'Sortez les brochettes 20 minutes avant la cuisson.',
        'Sur une braise bien grise, grillez 4 minutes par face.',
        'Mélangez la harissa avec le jus de citron, badigeonnez en fin de cuisson.',
        'Servez dans le pain tabouna avec la mechouia.',
      ],
      ar: [
        'أخرج الأسياخ قبل الطهي بـ20 دقيقة.',
        'على جمر رمادي جيد، اشوِ 4 دقائق لكل جهة.',
        'اخلط الهريسة مع عصير الليمون وادهن بها في نهاية الطهي.',
        'قدّمها في خبز الطابونة مع السلطة المشوية.',
      ],
    },
    product_slugs: ['brochettes-de-poulet-marinees'],
  },
  {
    id: 'r-ojja',
    slug: 'ojja-aux-merguez',
    title: { fr: 'Ojja aux merguez et aux œufs fermiers', ar: 'عجّة بالمرقاز والبيض البلدي' },
    intro: {
      fr: 'Le plat du soir en 20 minutes : tomates, merguez, poivrons, et les œufs qui prennent dessus.',
      ar: 'طبق المساء في 20 دقيقة: طماطم، مرقاز، فلفل، والبيض يستوي فوقها.',
    },
    image: '/images/recipes/recette-omelette.jpg',
    duration_min: 20,
    servings: 2,
    difficulty: 1,
    ingredients: {
      fr: ['4 œufs fermiers', '250 g de merguez de volaille', '3 tomates', '1 poivron vert', '2 gousses d’ail', '1 c. à s. de concentré de tomate', 'Harissa, carvi, sel'],
      ar: ['4 بيضات بلدية', '250 غ مرقاز دواجن', '3 طماطم', 'فلفلة خضراء', 'فصان ثوم', 'ملعقة كبيرة معجون طماطم', 'هريسة، كروية، ملح'],
    },
    steps: {
      fr: [
        'Faites revenir les merguez coupées en tronçons, réservez.',
        'Dans la même poêle, faites fondre l’ail, le poivron et le concentré, puis les tomates en dés. Laissez réduire 10 minutes.',
        'Remettez les merguez, cassez les œufs par-dessus, couvrez 3 minutes.',
        'Servez aussitôt avec du pain.',
      ],
      ar: [
        'حمّر المرقاز المقطّع ثم ضعه جانباً.',
        'في نفس المقلاة اطهُ الثوم والفلفل والمعجون ثم الطماطم المقطّعة. اتركها تتكاثف 10 دقائق.',
        'أعد المرقاز واكسر البيض فوقه وغطّه 3 دقائق.',
        'قدّمها فوراً مع الخبز.',
      ],
    },
    product_slugs: ['oeufs-fermiers-x6', 'merguez-de-volaille'],
  },
];

export const zones: DeliveryZone[] = [
  {
    id: 'z-korba',
    name: { fr: 'Korba et alentours', ar: 'قربة وضواحيها' },
    areas: { fr: 'Korba, Tazerka, Diar El Hojjaj, Bou Argoub', ar: 'قربة، تازركة، ديار الحجاج، بوعرقوب' },
    fee: 3,
    free_from: 60,
    lead_days: 0,
    active: true,
    sort: 1,
  },
  {
    id: 'z-cap-bon',
    name: { fr: 'Cap Bon nord', ar: 'شمال الوطن القبلي' },
    areas: { fr: 'Menzel Temime, Kélibia, Béni Khalled, Menzel Bouzelfa', ar: 'منزل تميم، قليبية، بني خلاد، منزل بوزلفة' },
    fee: 5,
    free_from: 100,
    lead_days: 1,
    active: true,
    sort: 2,
  },
  {
    id: 'z-nabeul',
    name: { fr: 'Nabeul et Hammamet', ar: 'نابل والحمامات' },
    areas: { fr: 'Nabeul, Dar Chaabane, Hammamet, Grombalia', ar: 'نابل، دار شعبان، الحمامات، قرمبالية' },
    fee: 7,
    free_from: 150,
    lead_days: 1,
    active: true,
    sort: 3,
  },
  {
    id: 'z-tunis',
    name: { fr: 'Grand Tunis', ar: 'تونس الكبرى' },
    areas: { fr: 'Tunis, La Marsa, Ariana, Ben Arous, Le Bardo', ar: 'تونس، المرسى، أريانة، بن عروس، باردو' },
    fee: 12,
    free_from: 250,
    lead_days: 1,
    active: true,
    sort: 4,
  },
];

export const slots: DeliverySlot[] = [
  { id: 's-matin', label: { fr: 'Matin', ar: 'صباحاً' }, from: '09:00', to: '12:00', days: [1, 2, 3, 4, 5, 6], active: true, sort: 1 },
  { id: 's-midi', label: { fr: 'Début d’après-midi', ar: 'بداية بعد الظهر' }, from: '13:00', to: '16:00', days: [1, 2, 3, 4, 5, 6], active: true, sort: 2 },
  { id: 's-soir', label: { fr: 'Fin de journée', ar: 'آخر النهار' }, from: '16:00', to: '19:00', days: [1, 2, 3, 4, 5, 6], active: true, sort: 3 },
];

export const settings: Settings = {
  shop_open: true,
  announcement: { fr: '', ar: '' },
  min_order: 20,
  max_days_ahead: 6,
  cutoff_time: '18:00',
  closed_days: [0],
};

export const offers: Offer[] = [
  {
    id: 'o-jour',
    kind: 'deal',
    eyebrow: { fr: 'Offre du jour', ar: 'عرض اليوم' },
    title: { fr: '-20 % sur les œufs fermiers', ar: '-20% على البيض البلدي' },
    subtitle: { fr: 'Sur toutes les boîtes, commandé avant 18 h', ar: 'على كل العلب، للطلبات قبل 18:00' },
    badge: { fr: '-20 %', ar: '-20%' },
    price: null,
    compare_at: null,
    image: '/images/products/oeufs.jpg',
    cta: { fr: 'Commander', ar: 'اطلب الآن' },
    link: '/produits/categorie/oeufs',
    ends_at: null,
    product_slugs: [],
    active: true,
    sort: 1,
  },
  {
    id: 'o-combo',
    kind: 'combo',
    eyebrow: { fr: 'Pack combiné', ar: 'باقة مشتركة' },
    title: { fr: 'Le pack braise du week-end', ar: 'باقة شواء نهاية الأسبوع' },
    subtitle: { fr: 'Merguez, brochettes et ailes, pour 6 personnes', ar: 'مرقاز وأسياخ وأجنحة، لستة أشخاص' },
    badge: { fr: 'Économisez 6 DT', ar: 'وفّر 6 د.ت' },
    price: 49.9,
    compare_at: 55.9,
    image: '/images/products/brochettes.jpg',
    cta: { fr: 'Ajouter le pack', ar: 'أضف الباقة' },
    link: '/produits/categorie/marines',
    ends_at: null,
    product_slugs: ['merguez-de-volaille', 'brochettes-de-poulet-marinees', 'ailes-de-poulet'],
    active: true,
    sort: 2,
  },
  {
    id: 'o-saison',
    kind: 'season',
    eyebrow: { fr: 'Spécial saison', ar: 'خاص بالموسم' },
    title: { fr: 'Le poulet du dimanche', ar: 'دجاج يوم الأحد' },
    subtitle: { fr: 'Poulet fermier entier et boîte de 12 œufs', ar: 'دجاجة بلدية كاملة وعلبة 12 بيضة' },
    badge: { fr: 'Économisez 3 DT', ar: 'وفّر 3 د.ت' },
    price: 29.9,
    compare_at: 32.9,
    image: '/images/products/poulet-entier.jpg',
    cta: { fr: 'Ajouter le pack', ar: 'أضف الباقة' },
    link: '/produits/poulet-fermier-entier',
    ends_at: null,
    product_slugs: ['poulet-fermier-entier', 'oeufs-fermiers-x12'],
    active: true,
    sort: 3,
  },
];

export const seed = { categories, products, recipes, zones, slots, settings, offers };
