/** Les illustrations détourées disponibles dans Art.astro. */
export type ArtName =
  | 'poussin-eclosion'
  | 'poussin'
  | 'famille-volaille'
  | 'famille-grain'
  | 'merci-fr'
  | 'merci-ar'
  | 'paiement-fr'
  | 'paiement-ar'
  | 'panier-oeufs'
  | 'medaille-premium'
  | 'badges-confiance'
  | 'footer-gauche'
  | 'footer-droite'
  | 'footer-collines'
  | 'footer-olivier'
  | 'footer-olivier-brin'
  | 'footer-oeufs-heureux'
  | 'footer-gout-local';
